#!/usr/bin/env python3
"""Scaffold a reusable read-only Codex monitor for long-running Linux jobs."""

from __future__ import annotations

import argparse
import shlex
import stat
from dataclasses import dataclass
from pathlib import Path


MANAGED_EXECUTABLES = {
    ".codex_monitor/run_command.sh",
    ".codex_monitor/scripts/hourly_check.sh",
    ".codex_monitor/scripts/install_systemd_timer.sh",
    ".codex_monitor/scripts/uninstall_systemd_timer.sh",
    ".codex_monitor/scripts/send_mail.py",
    "run_with_monitor.sh",
    "run_train_with_monitor.sh",
}


SMTP_PRESETS = {
    "qq.com": ("smtp.qq.com", 587, "starttls"),
    "foxmail.com": ("smtp.qq.com", 587, "starttls"),
    "gmail.com": ("smtp.gmail.com", 587, "starttls"),
    "outlook.com": ("smtp-mail.outlook.com", 587, "starttls"),
    "hotmail.com": ("smtp-mail.outlook.com", 587, "starttls"),
    "live.com": ("smtp-mail.outlook.com", 587, "starttls"),
    "163.com": ("smtp.163.com", 465, "ssl"),
    "126.com": ("smtp.126.com", 465, "ssl"),
    "yeah.net": ("smtp.yeah.net", 465, "ssl"),
}


@dataclass(frozen=True)
class InstallConfig:
    workspace: Path
    label: str
    systemd_basename: str
    job_service: str
    primary_log: str
    progress_log: str
    artifact_dirs: tuple[str, ...]
    process_grep: str
    codex_model: str
    run_command: str
    goal_mode: bool


README_TEMPLATE = """# @@LABEL@@ Codex Monitor

This folder contains a workspace-local Codex monitor for any long-running Linux job that should be watched over time and summarized into friendly reports.

Typical targets:

- model training;
- evaluation or benchmark runs;
- long goal-mode or batch Codex jobs;
- offline data processing with meaningful logs and artifacts.

The monitor provides:

- hourly read-only markdown reports;
- final completion or failure summaries;
- goal-mode terminal emails for `complete`, `blocked`, and `usageLimited`;
- optional SMTP email notification for the final result;
- a systemd user timer for periodic inspection;
- a wrapper that records start time, end time, exit code, and the local run log.

## Quick Start

1. Edit the actual job command:

```bash
.codex_monitor/run_command.sh
```

2. Review monitor config:

```bash
.codex_monitor/monitor.env
```

3. If email is wanted and `.codex_monitor/email.env` does not already exist:

```bash
cp .codex_monitor/email.env.example .codex_monitor/email.env
```

4. Start the long-running job through the wrapper:

```bash
./run_with_monitor.sh
```

Compatibility alias:

```bash
./run_train_with_monitor.sh
```

5. Generate one manual hourly report without sending mail:

```bash
CODEX_MONITOR_SKIP_EMAIL=1 .codex_monitor/scripts/hourly_check.sh
```

6. Install or remove the user timer:

```bash
.codex_monitor/scripts/install_systemd_timer.sh
.codex_monitor/scripts/uninstall_systemd_timer.sh
```

## Notes

- Linux only. The timer installer targets `systemd --user`.
- Codex reporting is read-only.
- Final email is sent only when the run is marked done or failed.
- For Codex goal runs, install with `--goal-mode` so the final email can distinguish `complete`, `blocked`, and `usageLimited`.
- Reports, snapshots, state files, and SMTP secrets should stay local and untracked.
"""


GITIGNORE_TEMPLATE = """email.env
reports/*.md
snapshots/*.txt
state/*
!reports/.gitkeep
!snapshots/.gitkeep
!state/.gitkeep
"""


EMAIL_ENV_TEMPLATE = """SMTP_HOST=@@SMTP_HOST@@
SMTP_PORT=@@SMTP_PORT@@
SMTP_SECURITY=@@SMTP_SECURITY@@
SMTP_USER=@@SMTP_USER@@
SMTP_PASS=@@SMTP_PASS@@
EMAIL_FROM=@@EMAIL_FROM@@
EMAIL_TO=@@EMAIL_TO@@
"""


MONITOR_ENV_TEMPLATE = """# Generated by TaskWatch. Edit as needed.
CODEX_MONITOR_LABEL=@@LABEL_SHELL@@
CODEX_MONITOR_SYSTEMD_BASENAME=@@SYSTEMD_BASENAME_SHELL@@
CODEX_MONITOR_JOB_SERVICE=@@JOB_SERVICE_SHELL@@
CODEX_MONITOR_PRIMARY_LOG=@@PRIMARY_LOG_SHELL@@
CODEX_MONITOR_PROGRESS_LOG=@@PROGRESS_LOG_SHELL@@
CODEX_MONITOR_ARTIFACT_DIRS=@@ARTIFACT_DIRS_SHELL@@
CODEX_MONITOR_PROCESS_GREP=@@PROCESS_GREP_SHELL@@
CODEX_MONITOR_CODEX_MODEL=@@CODEX_MODEL_SHELL@@
CODEX_MONITOR_GOAL_MODE=@@GOAL_MODE@@
"""


RUN_COMMAND_TEMPLATE = """#!/usr/bin/env bash
set -euo pipefail

WORKSPACE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$WORKSPACE"
exec bash -lc @@RUN_COMMAND_SHELL@@
"""


RUN_WRAPPER_TEMPLATE = """#!/usr/bin/env bash
set -euo pipefail

WORKSPACE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MONITOR_DIR="$WORKSPACE/.codex_monitor"
STATE_DIR="$MONITOR_DIR/state"
LOG_DIR="$STATE_DIR/logs"
mkdir -p "$STATE_DIR" "$LOG_DIR"

rm -f "$STATE_DIR/RUN_DONE" "$STATE_DIR/RUN_FAILED" "$STATE_DIR/NOTIFIED_DONE"
rm -f "$STATE_DIR/TRAIN_DONE" "$STATE_DIR/TRAIN_FAILED"
rm -f "$STATE_DIR/run_end_time.txt" "$STATE_DIR/run_exit_code.txt"
rm -f "$STATE_DIR/train_end_time.txt" "$STATE_DIR/train_exit_code.txt"

date '+%Y-%m-%d %H:%M:%S %Z' > "$STATE_DIR/run_start_time.txt"

timestamp="$(date '+%Y%m%d_%H%M%S')"
log_file="$LOG_DIR/run_${timestamp}.log"
printf '%s\n' "$log_file" > "$STATE_DIR/latest_run_log.txt"
printf '%s\n' ".codex_monitor/run_command.sh" > "$STATE_DIR/run_command.txt"

cd "$WORKSPACE"
set +e
"$MONITOR_DIR/run_command.sh" 2>&1 | tee "$log_file"
exit_code="${PIPESTATUS[0]}"
set -e

date '+%Y-%m-%d %H:%M:%S %Z' > "$STATE_DIR/run_end_time.txt"
printf '%s\n' "$exit_code" > "$STATE_DIR/run_exit_code.txt"

if [[ "$exit_code" -eq 0 ]]; then
  touch "$STATE_DIR/RUN_DONE"
else
  touch "$STATE_DIR/RUN_FAILED"
fi

exit "$exit_code"
"""


TRAIN_WRAPPER_COMPAT_TEMPLATE = """#!/usr/bin/env bash
set -euo pipefail
exec "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/run_with_monitor.sh" "$@"
"""


HOURLY_CHECK_TEMPLATE = """#!/usr/bin/env bash
set -euo pipefail

WORKSPACE="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MONITOR_DIR="$WORKSPACE/.codex_monitor"
REPORT_DIR="$MONITOR_DIR/reports"
SNAPSHOT_DIR="$MONITOR_DIR/snapshots"
STATE_DIR="$MONITOR_DIR/state"
LOCK_FILE="$STATE_DIR/hourly_check.lock"
CONFIG_FILE="$MONITOR_DIR/monitor.env"

mkdir -p "$REPORT_DIR" "$SNAPSHOT_DIR" "$STATE_DIR"

if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
fi

MONITOR_LABEL="${CODEX_MONITOR_LABEL:-Long Job}"
JOB_SERVICE="${CODEX_MONITOR_JOB_SERVICE:-}"
PRIMARY_LOG_REL="${CODEX_MONITOR_PRIMARY_LOG:-}"
PROGRESS_LOG_REL="${CODEX_MONITOR_PROGRESS_LOG:-}"
ARTIFACT_DIRS_STRING="${CODEX_MONITOR_ARTIFACT_DIRS:-logs outputs reports results artifacts}"
PROCESS_GREP="${CODEX_MONITOR_PROCESS_GREP:-python|bash|codex}"
GOAL_MODE="${CODEX_MONITOR_GOAL_MODE:-0}"

PRIMARY_LOG_PATH=""
if [[ -n "$PRIMARY_LOG_REL" ]]; then
  PRIMARY_LOG_PATH="$WORKSPACE/$PRIMARY_LOG_REL"
fi

PROGRESS_LOG_PATH=""
if [[ -n "$PROGRESS_LOG_REL" ]]; then
  PROGRESS_LOG_PATH="$WORKSPACE/$PROGRESS_LOG_REL"
fi

read -r -a ARTIFACT_DIRS <<< "$ARTIFACT_DIRS_STRING"

exec 9>"$LOCK_FILE"
if ! flock -n 9; then
  echo "another hourly_check.sh is already running"
  exit 0
fi

timestamp="$(date '+%Y%m%d_%H%M%S')"
SNAPSHOT="$SNAPSHOT_DIR/snapshot_${timestamp}.txt"
HOURLY_REPORT="$REPORT_DIR/hourly_report_${timestamp}.md"
FINAL_REPORT="$REPORT_DIR/final_report_${timestamp}.md"

append_cmd() {
  local title="$1"
  shift
  {
    printf '\n===== %s =====\n' "$title"
    "$@" 2>&1 || true
  } >> "$SNAPSHOT"
}

append_text() {
  local title="$1"
  local body="$2"
  {
    printf '\n===== %s =====\n' "$title"
    printf '%s\n' "$body"
  } >> "$SNAPSHOT"
}

state_exists() {
  local relative="$1"
  [[ -e "$STATE_DIR/$relative" ]]
}

state_read() {
  local relative="$1"
  if [[ -f "$STATE_DIR/$relative" ]]; then
    cat "$STATE_DIR/$relative" 2>/dev/null || true
  fi
}

collect_goal_status_lines() {
  local codex_home="${CODEX_HOME:-$HOME/.codex}"
  local sessions_root="$codex_home/sessions"
  if [[ "$GOAL_MODE" != "1" || ! -d "$sessions_root" || ! -f "$STATE_DIR/run_start_time.txt" ]]; then
    return 0
  fi
  while IFS= read -r session_file; do
    rg -n 'thread_goal_updated.*"status":"(complete|blocked|usageLimited)"' "$session_file" || true
  done < <(find "$sessions_root" -type f -name '*.jsonl' -newer "$STATE_DIR/run_start_time.txt" 2>/dev/null | sort)
}

detect_goal_terminal_state() {
  if [[ "$GOAL_MODE" != "1" ]]; then
    return 0
  fi

  local goal_status=""
  local goal_source=""
  local goal_line=""
  local run_log=""
  run_log="$(state_read latest_run_log.txt)"
  if [[ -n "$run_log" && -f "$run_log" ]]; then
    goal_line="$(grep -E "You've hit your usage limit|usage limit|Visit https://chatgpt.com/codex/settings/usage" "$run_log" 2>/dev/null | tail -n 1 || true)"
    if [[ -n "$goal_line" ]]; then
      goal_status="usageLimited"
      goal_source="$run_log"
    fi
  fi

  if [[ -z "$goal_status" ]]; then
    while IFS= read -r candidate_line; do
      [[ -z "$candidate_line" ]] && continue
      goal_line="$candidate_line"
    done < <(collect_goal_status_lines)
    case "$goal_line" in
      *'"status":"usageLimited"'*)
        goal_status="usageLimited"
        ;;
      *'"status":"blocked"'*)
        goal_status="blocked"
        ;;
      *'"status":"complete"'*)
        goal_status="complete"
        ;;
    esac
    if [[ -n "$goal_status" ]]; then
      goal_source="$(printf '%s\n' "$goal_line" | cut -d: -f1)"
    fi
  fi

  if [[ -n "$goal_status" ]]; then
    printf '%s\n' "$goal_status" > "$STATE_DIR/goal_final_status.txt"
    printf '%s\n' "$goal_source" > "$STATE_DIR/goal_final_status_source.txt"
    printf '%s\n' "$goal_line" > "$STATE_DIR/goal_final_status_line.txt"
  fi
}

maybe_mark_service_finished() {
  if state_exists RUN_DONE || state_exists RUN_FAILED || state_exists TRAIN_DONE || state_exists TRAIN_FAILED; then
    return 0
  fi

  if [[ -z "$JOB_SERVICE" ]]; then
    return 0
  fi

  local service_state="unknown"
  service_state="$(systemctl --user is-active "$JOB_SERVICE" 2>/dev/null || true)"
  if [[ "$service_state" == "active" || "$service_state" == "activating" ]]; then
    return 0
  fi
  if [[ -z "$service_state" ]]; then
    return 0
  fi

  local exit_status="unknown"
  exit_status="$(systemctl --user show "$JOB_SERVICE" -p ExecMainStatus --value 2>/dev/null || true)"

  date '+%Y-%m-%d %H:%M:%S %Z' > "$STATE_DIR/run_end_time.txt"
  printf '%s\n' "${exit_status:-unknown}" > "$STATE_DIR/run_exit_code.txt"
  if [[ "$exit_status" == "0" ]]; then
    touch "$STATE_DIR/RUN_DONE"
  else
    touch "$STATE_DIR/RUN_FAILED"
  fi
}

make_fallback_report() {
  local report_path="$1"
  local title="$2"
  cat > "$report_path" <<EOF
# $title

## 结论
Codex 自动巡检未能生成完整分析，已保留原始快照供人工查看。

## 当前状态
当前快照见：$SNAPSHOT

## 风险
Codex exec 失败或不可用。

## 建议
查看快照、运行日志、systemd 用户服务状态和最新结果产物。
EOF
}

append_codex_error_summary() {
  local report_path="$1"
  local codex_log="$2"
  {
    printf '\n## Codex Exec\n'
    printf 'Codex exec failed. Log path: `%s`\n' "$codex_log"
    printf '\nRecent connection errors:\n\n'
    grep -E 'ERROR|error sending request|failed to connect|stream disconnected|Transport channel closed' "$codex_log" 2>/dev/null \
      | tail -n 12 \
      | sed 's/^/- /' || true
  } >> "$report_path"
}

run_codex_report() {
  local report_path="$1"
  local title="$2"
  local prompt="$3"
  local codex_log="$STATE_DIR/codex_exec_${timestamp}.log"
  local codex_bin="${CODEX_MONITOR_CODEX_BIN:-}"
  if [[ -z "$codex_bin" ]]; then
    codex_bin="$(command -v codex || true)"
  fi
  if [[ -z "$codex_bin" || ! -x "$codex_bin" ]]; then
    make_fallback_report "$report_path" "$title"
    return 0
  fi

  local codex_dir
  codex_dir="$(dirname "$codex_bin")"
  if ! timeout "${CODEX_MONITOR_CODEX_TIMEOUT:-20m}" env PATH="$codex_dir:$PATH" "$codex_bin" exec --ephemeral --sandbox read-only -c 'approval_policy="never"' -m "${CODEX_MONITOR_CODEX_MODEL:-gpt-5.4-mini}" --cd "$WORKSPACE" -o "$report_path" "$prompt" < "$SNAPSHOT" > "$codex_log" 2>&1; then
    make_fallback_report "$report_path" "$title"
    append_codex_error_summary "$report_path" "$codex_log"
  fi
}

{
  printf '===== Snapshot metadata =====\n'
  printf 'timestamp=%s\n' "$(date '+%Y-%m-%d %H:%M:%S %Z')"
  printf 'workspace=%s\n' "$WORKSPACE"
  printf 'label=%s\n' "$MONITOR_LABEL"
  printf 'job_service=%s\n' "$JOB_SERVICE"
  printf 'primary_log=%s\n' "$PRIMARY_LOG_REL"
  printf 'progress_log=%s\n' "$PROGRESS_LOG_REL"
  printf 'artifact_dirs=%s\n' "$ARTIFACT_DIRS_STRING"
} > "$SNAPSHOT"

append_cmd "current time" date '+%Y-%m-%d %H:%M:%S %Z'
append_cmd "git commit" git -C "$WORKSPACE" rev-parse HEAD
append_cmd "git status" git -C "$WORKSPACE" status --short
append_cmd "state files" find "$STATE_DIR" -maxdepth 2 -type f -printf '%TY-%Tm-%Td %TH:%TM %p\n'

if [[ -n "$JOB_SERVICE" ]]; then
  append_cmd "job service status" systemctl --user status "$JOB_SERVICE" --no-pager
else
  append_text "job service status" "no user systemd service configured"
fi

append_cmd "matching processes" env PROCESS_GREP="$PROCESS_GREP" bash -lc 'ps -eo pid,ppid,etime,stat,cmd | grep -E "$PROCESS_GREP" | grep -v grep'
append_cmd "nvidia-smi" nvidia-smi
append_cmd "disk usage" df -h "$WORKSPACE" "$MONITOR_DIR" /tmp

for dir in "${ARTIFACT_DIRS[@]}"; do
  if [[ -n "$dir" && -e "$WORKSPACE/$dir" ]]; then
    append_cmd "artifact dir size: $dir" du -sh "$WORKSPACE/$dir"
    append_cmd "recent artifacts: $dir" bash -lc "find '$WORKSPACE/$dir' -type f -printf '%T@ %TY-%Tm-%Td %TH:%TM %p\n' 2>/dev/null | sort -nr | head -n 20"
  fi
done

if state_exists latest_run_log.txt; then
  append_cmd "latest run log path" cat "$STATE_DIR/latest_run_log.txt"
  append_cmd "latest run log tail" bash -lc "tail -n 120 \"$(cat '$STATE_DIR/latest_run_log.txt')\" 2>/dev/null"
fi

if [[ -n "$PRIMARY_LOG_PATH" ]]; then
  append_cmd "primary log tail" bash -lc "tail -n 120 '$PRIMARY_LOG_PATH' 2>/dev/null"
  append_cmd "primary log signals" bash -lc "grep -E 'iteration|epoch|step|progress|checkpoint|saved|artifact|error|warning|failed|success|complete|ETA|reward|loss|accuracy|metric' '$PRIMARY_LOG_PATH' 2>/dev/null | tail -n 120"
else
  append_text "primary log tail" "no primary log configured"
fi

if [[ -n "$PROGRESS_LOG_PATH" ]]; then
  append_cmd "progress log timeline" bash -lc "tail -n 120 '$PROGRESS_LOG_PATH' 2>/dev/null"
else
  append_text "progress log timeline" "no progress log configured"
fi

if [[ "$GOAL_MODE" == "1" ]]; then
  goal_snapshot_lines="$(collect_goal_status_lines | tail -n 20)"
  if [[ -n "$goal_snapshot_lines" ]]; then
    append_text "goal status events" "$goal_snapshot_lines"
  else
    append_text "goal status events" "no goal status events found in recent Codex sessions"
  fi
else
  append_text "goal status events" "goal mode disabled"
fi

maybe_mark_service_finished
detect_goal_terminal_state

hourly_title="${MONITOR_LABEL} 小时巡检报告"
hourly_prompt='你是长时间运行任务的只读巡检员。只能基于输入快照分析；不要编造；不要修改文件；不要重启任务；没有看到的信息写“当前快照未提供”。请输出中文 markdown，必须包含这些标题：# 小时巡检报告、## 结论、## 当前状态、## 进展信号、## 最新产物、## 风险、## 建议。尽量用表格总结当前状态、最近日志信号、最近产物和异常；如果缺少结构化指标，就明确写缺少什么。不要大段粘贴原始快照。'
run_codex_report "$HOURLY_REPORT" "$hourly_title" "$hourly_prompt"

if state_exists RUN_DONE || state_exists RUN_FAILED || state_exists TRAIN_DONE || state_exists TRAIN_FAILED; then
  if [[ ! -e "$STATE_DIR/NOTIFIED_DONE" ]]; then
    final_kind="运行完成通知"
    goal_final_status="$(state_read goal_final_status.txt)"
    case "$goal_final_status" in
      complete)
        final_kind="Goal 完成通知"
        ;;
      blocked)
        final_kind="Goal 阻塞通知"
        ;;
      usageLimited)
        final_kind="Goal 额度触顶通知"
        ;;
    esac
    final_title="${MONITOR_LABEL} ${final_kind}"
    final_prompt='你是长时间运行任务的只读完成总结员。只能基于输入快照分析；不要编造；不要修改文件；不要重启任务；没有看到的信息写“当前快照未提供”。如果快照里出现 goal status，请明确区分 `complete`、`blocked`、`usageLimited`，并给出证据来源。请输出中文 markdown，必须包含这些标题：# 运行完成通知、## 最终结论、## 运行时间、## 退出状态、## 关键进展回顾、## 结果产物、## 异常信息、## 后续建议。最终结论要明确说明任务是否成功、依据是什么、哪些结论还需要人工确认。不要大段粘贴原始快照。'
    run_codex_report "$FINAL_REPORT" "$final_title" "$final_prompt"

    if [[ "${CODEX_MONITOR_DRY_RUN:-0}" == "1" || "${CODEX_MONITOR_SKIP_EMAIL:-0}" == "1" ]]; then
      echo "email skipped by dry-run or CODEX_MONITOR_SKIP_EMAIL"
    elif [[ -f "$MONITOR_DIR/email.env" ]]; then
      python3 "$MONITOR_DIR/scripts/send_mail.py" "$final_title" "$FINAL_REPORT"
      touch "$STATE_DIR/NOTIFIED_DONE"
    else
      echo "email skipped; missing $MONITOR_DIR/email.env"
    fi
  fi
fi

echo "snapshot: $SNAPSHOT"
echo "hourly_report: $HOURLY_REPORT"
"""


INSTALL_TIMER_TEMPLATE = """#!/usr/bin/env bash
set -euo pipefail

WORKSPACE="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MONITOR_DIR="$WORKSPACE/.codex_monitor"
CONFIG_FILE="$MONITOR_DIR/monitor.env"
if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
fi

BASENAME="${CODEX_MONITOR_SYSTEMD_BASENAME:-codex-long-job-monitor}"
MONITOR_LABEL="${CODEX_MONITOR_LABEL:-Long Job}"
USER_SYSTEMD_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
SERVICE_PATH="$USER_SYSTEMD_DIR/${BASENAME}.service"
TIMER_PATH="$USER_SYSTEMD_DIR/${BASENAME}.timer"
CODEX_BIN="$(command -v codex || true)"
NODE_BIN="$(command -v node || true)"

if [[ -z "$CODEX_BIN" ]]; then
  echo "codex was not found in PATH; fallback reports will still work." >&2
fi

proxy_env_lines=""
for key in http_proxy https_proxy all_proxy no_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY CODEX_NETWORK_PROXY_ACTIVE; do
  if [[ -n "${!key:-}" ]]; then
    proxy_env_lines+="Environment=$key=${!key}"$'\n'
  fi
done

mkdir -p "$USER_SYSTEMD_DIR"

cat > "$SERVICE_PATH" <<EOF
[Unit]
Description=${MONITOR_LABEL} Codex read-only hourly monitor

[Service]
Type=oneshot
WorkingDirectory=$WORKSPACE
ExecStart=$WORKSPACE/.codex_monitor/scripts/hourly_check.sh
TimeoutStartSec=20min
Environment=CODEX_MONITOR_CODEX_BIN=$CODEX_BIN
Environment=CODEX_MONITOR_CODEX_MODEL=${CODEX_MONITOR_CODEX_MODEL:-gpt-5.4-mini}
Environment=PATH=$(dirname "${NODE_BIN:-/usr/bin/node}"):/usr/local/bin:/usr/bin:/bin
$proxy_env_lines
EOF

cat > "$TIMER_PATH" <<EOF
[Unit]
Description=Run ${MONITOR_LABEL} Codex monitor hourly

[Timer]
OnBootSec=5min
OnUnitActiveSec=1h
Persistent=true
Unit=${BASENAME}.service

[Install]
WantedBy=timers.target
EOF

systemctl --user daemon-reload
systemctl --user enable --now "${BASENAME}.timer"
systemctl --user list-timers "${BASENAME}.timer" --no-pager
"""


UNINSTALL_TIMER_TEMPLATE = """#!/usr/bin/env bash
set -euo pipefail

WORKSPACE="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MONITOR_DIR="$WORKSPACE/.codex_monitor"
CONFIG_FILE="$MONITOR_DIR/monitor.env"
if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
fi

BASENAME="${CODEX_MONITOR_SYSTEMD_BASENAME:-codex-long-job-monitor}"
systemctl --user disable --now "${BASENAME}.timer" 2>/dev/null || true
systemctl --user stop "${BASENAME}.service" 2>/dev/null || true
systemctl --user daemon-reload

echo "Removed ${BASENAME} timer. Reports, snapshots, state files, and email.env were not deleted."
"""


SEND_MAIL_TEMPLATE = """#!/usr/bin/env python3
\"\"\"Send a structured UTF-8 plain-text final email through SMTP.\"\"\"

from __future__ import annotations

import argparse
import json
import os
import re
import smtplib
import ssl
from datetime import datetime, timezone
from email.message import EmailMessage
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo


WORKSPACE = Path(__file__).resolve().parents[2]
MONITOR_DIR = WORKSPACE / ".codex_monitor"
STATE_DIR = MONITOR_DIR / "state"
DEFAULT_ENV_FILE = WORKSPACE / ".codex_monitor" / "email.env"
MONITOR_ENV_FILE = WORKSPACE / ".codex_monitor" / "monitor.env"
CODEX_HOME = Path(os.environ.get("CODEX_HOME", Path.home() / ".codex"))
REQUIRED_KEYS = ("SMTP_HOST", "SMTP_PORT", "SMTP_SECURITY", "SMTP_USER", "SMTP_PASS", "EMAIL_FROM", "EMAIL_TO")
TERMINAL_STATUSES = {"complete", "blocked", "usageLimited"}
DISPLAY_TZ = ZoneInfo("Asia/Shanghai")
ARCHIVE_ATTEMPT_MARKERS = (
    "archive_worklog.py",
    "lark-worklog-archive",
    "今日归档",
    "今天归档",
    "同步到飞书工作记录",
)
ARCHIVE_SUCCESS_MARKERS = (
    "Updated worklog ",
    "已记录到飞书",
    "Monthly document:",
)
ARCHIVE_FAILURE_MARKERS = (
    "Verification failed",
    "need_user_authorization",
    "Repair failed",
    "archive failed",
)


def _load_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        raise SystemExit(f"email config missing: {path}")

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise SystemExit(f"invalid email config line in {path}: {raw_line!r}")
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def _merged_config(path: Path) -> dict[str, str]:
    config = _load_env_file(path)
    for key in REQUIRED_KEYS:
        if key in os.environ and os.environ[key]:
            config[key] = os.environ[key]
    missing = [key for key in REQUIRED_KEYS if not config.get(key)]
    if missing:
        raise SystemExit("email config incomplete; missing: " + ", ".join(missing))
    return config


def _load_monitor_env(path: Path = MONITOR_ENV_FILE) -> dict[str, str]:
    if not path.exists():
        return {}
    return _load_env_file(path)


def _read_state(name: str) -> str:
    path = STATE_DIR / name
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace").strip()


def parse_timestamp(value: Any) -> datetime | None:
    if value is None or value == "":
        return None
    if isinstance(value, datetime):
        if value.tzinfo is None:
            return value.replace(tzinfo=timezone.utc)
        return value
    if isinstance(value, (int, float)):
        seconds = float(value)
        if abs(seconds) > 1_000_000_000_000:
            seconds /= 1000.0
        try:
            return datetime.fromtimestamp(seconds, tz=timezone.utc)
        except (OverflowError, OSError, ValueError):
            return None
    if not isinstance(value, str):
        return None
    text = value.strip()
    if not text:
        return None
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError:
        parsed = None
    if parsed is not None:
        if parsed.tzinfo is None:
            return parsed.replace(tzinfo=timezone.utc)
        return parsed
    for suffix, tzinfo in ((" Asia/Shanghai", DISPLAY_TZ), (" CST", DISPLAY_TZ), (" UTC", timezone.utc)):
        if text.endswith(suffix):
            raw = text[: -len(suffix)]
            try:
                parsed = datetime.strptime(raw, "%Y-%m-%d %H:%M:%S")
            except ValueError:
                return None
            return parsed.replace(tzinfo=tzinfo)
    return None


def format_timestamp(value: Any) -> str:
    parsed = parse_timestamp(value)
    if parsed is None:
        return "unknown"
    local = parsed.astimezone(DISPLAY_TZ)
    return local.strftime("%Y-%m-%d %H:%M:%S") + " Asia/Shanghai"


def format_duration(start: datetime | None, end: datetime | None) -> str:
    if start is None or end is None:
        return "unknown"
    seconds = max(0, int((end - start).total_seconds()))
    if seconds < 60:
        return f"{seconds}秒"
    minutes, remaining_seconds = divmod(seconds, 60)
    hours, remaining_minutes = divmod(minutes, 60)
    days, remaining_hours = divmod(hours, 24)
    parts: list[str] = []
    if days:
        parts.append(f"{days}天")
    if remaining_hours:
        parts.append(f"{remaining_hours}小时")
    if remaining_minutes:
        parts.append(f"{remaining_minutes}分钟")
    if remaining_seconds and not parts:
        parts.append(f"{remaining_seconds}秒")
    return "".join(parts) if parts else "0秒"


def normalize_text(text: str, limit: int = 240) -> str:
    compact = " ".join(text.split())
    if len(compact) <= limit:
        return compact
    return compact[: limit - 3].rstrip() + "..."


def strip_markdown(text: str) -> str:
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    return text.replace("`", "")


def summarize_task_name(text: str, limit: int = 120) -> str:
    candidate = strip_markdown(text).strip()
    if not candidate:
        return "unknown"
    for line in candidate.splitlines():
        line = line.strip()
        if line:
            candidate = line
            break
    for separator in ("。", "；", ";"):
        if separator in candidate:
            candidate = candidate.split(separator, 1)[0].strip()
    return normalize_text(candidate, limit=limit)


def is_noise_fragment(text: str) -> bool:
    stripped = text.strip()
    if not stripped:
        return True
    if stripped.startswith('{"cmd":') or stripped.startswith("{'cmd':"):
        return True
    if stripped.startswith("rg ") or stripped.startswith("grep "):
        return True
    noise_markers = ('"workdir":', '"yield_time_ms":', '"max_output_tokens":', '"cmd":')
    return any(marker in stripped for marker in noise_markers)


def humanize_archive_detail(detail: str) -> str:
    cleaned = strip_markdown(detail).strip()
    if not cleaned or is_noise_fragment(cleaned):
        return ""
    lowered = cleaned.lower()
    if "updated worklog " in lowered or "monthly document:" in lowered or "已记录到飞书" in cleaned:
        monthly_doc = ""
        match = re.search(r"Monthly document:\s*([^\n]+)", cleaned)
        if match:
            monthly_doc = match.group(1).strip()
        if monthly_doc:
            return f"已写入飞书工作记录（{monthly_doc}）。"
        return "已写入飞书工作记录。"
    if "need_user_authorization" in lowered:
        return "归档未完成：飞书授权已失效，需要重新授权后重试。"
    if "invalid utf-8" in lowered or ".pyc" in lowered or "__pycache__" in lowered:
        return "归档未完成：归档校验扫到了缓存或二进制文件，需跳过这类文件后重试。"
    if "verification failed" in lowered:
        return "归档未完成：归档校验失败，需检查归档输出后重试。"
    if "repair failed" in lowered or "archive failed" in lowered:
        return "归档未完成：归档流程执行失败，需要检查报错后重试。"
    return normalize_text(cleaned, limit=200)


def build_result_summary(status: str, task_name: str, archive_status: str, archive_detail: str = "") -> str:
    if status in {"complete", "done"}:
        conclusion = "goal 已完成。" if status == "complete" else "任务已完成。"
        result = f"已完成「{task_name}」，Codex 正常收尾。"
        next_step = "无需人工介入；如需要沉淀记录，可查看归档状态和 transcript。"
    elif status == "blocked":
        conclusion = "goal 未完成，当前处于 blocked。"
        result = f"「{task_name}」被阻塞，尚未达到完成状态。"
        next_step = "需要查看阻塞原因，决定补充信息、授权、环境修复或重新运行。"
    elif status == "usageLimited":
        conclusion = "goal 未完成，Codex 使用额度已触顶。"
        result = f"「{task_name}」因额度限制中断。"
        next_step = "等待额度恢复或切换可用额度后继续。"
    elif status == "failed":
        conclusion = "任务失败。"
        result = f"「{task_name}」运行失败，尚未达到完成状态。"
        next_step = "需要检查失败原因、日志和最新产物。"
    else:
        conclusion = "任务状态未知。"
        result = f"「{task_name}」已触发终态通知，但没有可识别的完成状态。"
        next_step = "需要查看 transcript 或运行日志确认真实结果。"

    lines = [
        f"- 结论：{conclusion}",
        f"- 主要结果：{result}",
        f"- 归档状态：{archive_status}",
    ]
    if archive_detail:
        lines.append(f"- 归档说明：{archive_detail}")
    lines.append(f"- 后续处理：{next_step}")
    return "\n".join(lines)


def extract_text_fragments(value: Any) -> list[str]:
    fragments: list[str] = []
    if isinstance(value, str):
        fragments.append(value)
        return fragments
    if isinstance(value, list):
        for item in value:
            fragments.extend(extract_text_fragments(item))
        return fragments
    if isinstance(value, dict):
        direct = value.get("text")
        if isinstance(direct, str):
            fragments.append(direct)
        for key in ("input_text", "output_text", "message", "content", "arguments", "output"):
            if key in value:
                fragments.extend(extract_text_fragments(value[key]))
        return fragments
    return fragments

def parse_goal_event(raw_line: str) -> dict[str, Any] | None:
    try:
        item = json.loads(raw_line)
    except json.JSONDecodeError:
        return None
    if item.get("type") != "event_msg":
        return None
    payload = item.get("payload") or {}
    if payload.get("type") != "thread_goal_updated":
        return None
    goal = payload.get("goal") or {}
    status = goal.get("status")
    if status not in TERMINAL_STATUSES:
        return None
    return {
        "status": status,
        "objective": goal.get("objective", ""),
        "turn_id": payload.get("turnId", ""),
        "updated_at": goal.get("updatedAt", ""),
        "timestamp": item.get("timestamp", ""),
        "source": "thread_goal_updated",
    }


def resolve_goal_transcript() -> Path | None:
    candidate = _read_state("goal_final_status_source.txt")
    if candidate:
        path = Path(candidate).expanduser()
        if path.exists() and path.suffix == ".jsonl":
            return path
    return None


def parse_transcript_context(transcript_path: Path) -> dict[str, str]:
    latest_goal_event: dict[str, Any] | None = None
    archive_attempted = False
    archive_success = ""
    archive_failure = ""
    for raw_line in transcript_path.read_text(encoding="utf-8", errors="replace").splitlines():
        event = parse_goal_event(raw_line)
        if event is not None:
            latest_goal_event = event
        try:
            item = json.loads(raw_line)
        except json.JSONDecodeError:
            continue
        payload = item.get("payload") or {}
        if item.get("type") != "response_item" or payload.get("type") != "function_call_output":
            continue
        text_sources = [
            normalize_text(fragment, limit=800)
            for fragment in extract_text_fragments(payload.get("output"))
            if fragment.strip()
        ]
        for source in text_sources:
            if is_noise_fragment(source):
                continue
            lower = source.lower()
            if any(marker.lower() in lower for marker in ARCHIVE_ATTEMPT_MARKERS):
                archive_attempted = True
            if not archive_success and any(marker.lower() in lower for marker in ARCHIVE_SUCCESS_MARKERS):
                archive_success = source
            if not archive_failure and any(marker.lower() in lower for marker in ARCHIVE_FAILURE_MARKERS):
                archive_failure = source
    archive_detail = humanize_archive_detail(archive_success or archive_failure)
    return {
        "objective": summarize_task_name(str((latest_goal_event or {}).get("objective", "")).strip(), limit=160),
        "goal_updated_at": str((latest_goal_event or {}).get("updated_at", "")),
        "goal_event_timestamp": str((latest_goal_event or {}).get("timestamp", "")),
        "archive_status": (
            "已完成"
            if archive_success
            else "尝试过，但未确认成功"
            if archive_attempted and archive_failure
            else "检测到归档动作，但未确认成功"
            if archive_attempted
            else "未检测到"
        ),
        "archive_detail": archive_detail,
    }


def summarize_status(status: str, exit_code: str) -> str:
    if status == "complete":
        return "已完成，goal 正常收尾。"
    if status == "blocked":
        return "未完成，goal 已进入 blocked，需要人工处理阻塞项。"
    if status == "usageLimited":
        return "未完成，Codex 使用额度已触顶。"
    if status == "failed":
        return f"任务以失败状态结束，退出码为 {exit_code or 'unknown'}。"
    if status == "done":
        return f"任务已结束，退出码为 {exit_code or '0'}。"
    return "状态未知。"


def intervention_status(status: str) -> str:
    if status in {"complete", "done"}:
        return "否"
    if status == "blocked":
        return "是，需要查看阻塞原因并决定下一步。"
    if status == "usageLimited":
        return "是，需要等待额度恢复或切换可用额度后重试。"
    if status == "failed":
        return "是，需要检查失败原因、日志和最新产物。"
    return "unknown"


def collect_context() -> dict[str, Any]:
    monitor_env = _load_monitor_env()
    label = summarize_task_name(monitor_env.get("CODEX_MONITOR_LABEL", WORKSPACE.name), limit=160)
    goal_mode = monitor_env.get("CODEX_MONITOR_GOAL_MODE", "0") == "1"
    run_start = parse_timestamp(_read_state("run_start_time.txt"))
    run_end = parse_timestamp(_read_state("run_end_time.txt") or _read_state("train_end_time.txt"))
    exit_code = _read_state("run_exit_code.txt") or _read_state("train_exit_code.txt")

    status = ""
    if _read_state("goal_final_status.txt") in TERMINAL_STATUSES:
        status = _read_state("goal_final_status.txt")
    elif (STATE_DIR / "RUN_FAILED").exists() or (STATE_DIR / "TRAIN_FAILED").exists():
        status = "failed"
    elif (STATE_DIR / "RUN_DONE").exists() or (STATE_DIR / "TRAIN_DONE").exists():
        status = "done"

    transcript_path = resolve_goal_transcript()
    transcript_context = parse_transcript_context(transcript_path) if transcript_path else {}

    task_name = transcript_context.get("objective") or label
    archive_status = transcript_context.get("archive_status") or ("未检测到" if goal_mode else "不适用")
    archive_detail = transcript_context.get("archive_detail") or ""
    finished_at = run_end or parse_timestamp(transcript_context.get("goal_updated_at") or transcript_context.get("goal_event_timestamp"))

    return {
        "status": status or "unknown",
        "task_name": task_name,
        "archive_status": archive_status,
        "archive_detail": archive_detail,
        "started_at": run_start,
        "finished_at": finished_at,
        "exit_code": exit_code or "unknown",
        "goal_transcript": str(transcript_path) if transcript_path else "",
    }


def build_email_subject(context: dict[str, Any]) -> str:
    task_name = summarize_task_name(str(context.get("task_name", "")).strip(), limit=48)
    if task_name and task_name != "unknown":
        return f"goal:{task_name}"
    return "goal:unknown"


def build_email_body(subject: str, _body_text: str, context: dict[str, Any]) -> str:
    result_summary = build_result_summary(
        str(context["status"]),
        str(context["task_name"]),
        str(context["archive_status"]),
        str(context.get("archive_detail", "")),
    )
    lines = [
        subject,
        "",
        "任务概况",
        f"- 任务是什么：{context['task_name']}",
        f"- 完成情况：{summarize_status(context['status'], context['exit_code'])}",
        f"- 是否需要介入：{intervention_status(context['status'])}",
        f"- 是否完成归档：{context['archive_status']}",
        f"- 完成时间：{format_timestamp(context['finished_at'])}",
        f"- 花了多久：{format_duration(context['started_at'], context['finished_at'])}",
        "",
        "结果摘要",
        result_summary,
        "",
        "运行信息",
        f"- 工作目录：{WORKSPACE}",
        f"- monitor 标签：{context['task_name']}",
        f"- 退出码：{context['exit_code']}",
        f"- goal transcript：{context['goal_transcript'] or 'unknown'}",
        f"- 启动时间：{format_timestamp(context['started_at'])}",
        f"- 完成判定来源：{context['status']}",
    ]
    return "\\n".join(lines).rstrip() + "\\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("subject", help="Email subject.")
    parser.add_argument("body_file", help="Path to a UTF-8 plain-text body file.")
    parser.add_argument("--env-file", default=str(DEFAULT_ENV_FILE), help="Path to SMTP env file.")
    args = parser.parse_args()

    env_file = Path(args.env_file).expanduser().resolve()
    body_file = Path(args.body_file).expanduser().resolve()
    if not body_file.exists():
        raise SystemExit(f"body file missing: {body_file}")

    config = _merged_config(env_file)
    smtp_port = int(config["SMTP_PORT"])
    security = config["SMTP_SECURITY"].strip().lower()
    context = collect_context()
    email_subject = build_email_subject(context)
    body_text = build_email_body(email_subject, body_file.read_text(encoding="utf-8"), context)

    message = EmailMessage()
    message["Subject"] = email_subject
    message["From"] = config["EMAIL_FROM"]
    message["To"] = config["EMAIL_TO"]
    message.set_content(body_text, subtype="plain", charset="utf-8")

    if security == "ssl":
        context = ssl.create_default_context()
        with smtplib.SMTP_SSL(config["SMTP_HOST"], smtp_port, timeout=30, context=context) as smtp:
            smtp.login(config["SMTP_USER"], config["SMTP_PASS"])
            smtp.send_message(message)
    else:
        context = ssl.create_default_context()
        with smtplib.SMTP(config["SMTP_HOST"], smtp_port, timeout=30) as smtp:
            smtp.ehlo()
            if security == "starttls":
                smtp.starttls(context=context)
                smtp.ehlo()
            smtp.login(config["SMTP_USER"], config["SMTP_PASS"])
            smtp.send_message(message)

    print(f"sent email to {config['EMAIL_TO']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
"""


def shell_quote(value: str) -> str:
    return shlex.quote(value)


def render(template: str, replacements: dict[str, str]) -> str:
    rendered = template
    for key, value in replacements.items():
        rendered = rendered.replace(f"@@{key}@@", value)
    return rendered


def infer_smtp(sender_email: str) -> tuple[str, int, str]:
    domain = sender_email.rsplit("@", 1)[-1].lower()
    if domain in SMTP_PRESETS:
        return SMTP_PRESETS[domain]
    return (f"smtp.{domain}", 587, "starttls")


def build_replacements(config: InstallConfig) -> dict[str, str]:
    return {
        "LABEL": config.label,
        "LABEL_SHELL": shell_quote(config.label),
        "SYSTEMD_BASENAME_SHELL": shell_quote(config.systemd_basename),
        "JOB_SERVICE_SHELL": shell_quote(config.job_service),
        "PRIMARY_LOG_SHELL": shell_quote(config.primary_log),
        "PROGRESS_LOG_SHELL": shell_quote(config.progress_log),
        "ARTIFACT_DIRS_SHELL": shell_quote(" ".join(config.artifact_dirs)),
        "PROCESS_GREP_SHELL": shell_quote(config.process_grep),
        "CODEX_MODEL_SHELL": shell_quote(config.codex_model),
        "RUN_COMMAND_SHELL": shell_quote(config.run_command),
        "GOAL_MODE": "1" if config.goal_mode else "0",
    }


def build_file_map(config: InstallConfig) -> dict[str, str]:
    replacements = build_replacements(config)
    return {
        ".codex_monitor/README.md": render(README_TEMPLATE, replacements),
        ".codex_monitor/.gitignore": GITIGNORE_TEMPLATE,
        ".codex_monitor/email.env.example": EMAIL_ENV_TEMPLATE.replace("@@SMTP_HOST@@", "smtp.qq.com").replace("@@SMTP_PORT@@", "587").replace("@@SMTP_SECURITY@@", "starttls").replace("@@SMTP_USER@@", "your_mail@example.com").replace("@@SMTP_PASS@@", "your_smtp_authorization_code").replace("@@EMAIL_FROM@@", "your_mail@example.com").replace("@@EMAIL_TO@@", "target_mail@example.com"),
        ".codex_monitor/monitor.env": render(MONITOR_ENV_TEMPLATE, replacements),
        ".codex_monitor/run_command.sh": render(RUN_COMMAND_TEMPLATE, replacements),
        ".codex_monitor/scripts/hourly_check.sh": render(HOURLY_CHECK_TEMPLATE, replacements),
        ".codex_monitor/scripts/install_systemd_timer.sh": render(INSTALL_TIMER_TEMPLATE, replacements),
        ".codex_monitor/scripts/uninstall_systemd_timer.sh": render(UNINSTALL_TIMER_TEMPLATE, replacements),
        ".codex_monitor/scripts/send_mail.py": SEND_MAIL_TEMPLATE,
        ".codex_monitor/reports/.gitkeep": "",
        ".codex_monitor/snapshots/.gitkeep": "",
        ".codex_monitor/state/.gitkeep": "",
        "run_with_monitor.sh": RUN_WRAPPER_TEMPLATE,
        "run_train_with_monitor.sh": TRAIN_WRAPPER_COMPAT_TEMPLATE,
    }


def build_email_env(sender_email: str, recipient_email: str, sender_password: str, smtp_host: str | None, smtp_port: int | None, smtp_security: str | None) -> str:
    host, port, security = infer_smtp(sender_email)
    if smtp_host:
        host = smtp_host
    if smtp_port:
        port = smtp_port
    if smtp_security:
        security = smtp_security
    replacements = {
        "SMTP_HOST": host,
        "SMTP_PORT": str(port),
        "SMTP_SECURITY": security,
        "SMTP_USER": sender_email,
        "SMTP_PASS": sender_password,
        "EMAIL_FROM": sender_email,
        "EMAIL_TO": recipient_email,
    }
    return render(EMAIL_ENV_TEMPLATE, replacements)


def print_install_summary(workspace: Path, config: InstallConfig, *, email_enabled: bool, smtp_host: str | None, smtp_port: int | None, smtp_security: str | None) -> None:
    print(f"[ok] installed monitor scaffold into {workspace}")
    print(f"[summary] label: {config.label}")
    print(f"[summary] run wrapper: {workspace / 'run_with_monitor.sh'}")
    print(f"[summary] command file: {workspace / '.codex_monitor' / 'run_command.sh'}")
    print(f"[summary] config file: {workspace / '.codex_monitor' / 'monitor.env'}")
    print(f"[summary] goal mode: {'enabled' if config.goal_mode else 'disabled'}")
    if email_enabled:
        print(f"[summary] email: enabled via {smtp_host}:{smtp_port} ({smtp_security})")
    else:
        print(f"[summary] email: not configured; fill {workspace / '.codex_monitor' / 'email.env'} later if needed")
    print("[next] edit .codex_monitor/run_command.sh if the inferred command is not final")
    print("[next] start the job with ./run_with_monitor.sh")
    print("[next] test one report with CODEX_MONITOR_SKIP_EMAIL=1 .codex_monitor/scripts/hourly_check.sh")
    print("[next] install the timer with .codex_monitor/scripts/install_systemd_timer.sh")


def write_files(workspace: Path, file_map: dict[str, str], *, force: bool, dry_run: bool) -> None:
    for relative in file_map:
        target = workspace / relative
        if target.exists() and not force:
            raise SystemExit(f"refusing to overwrite existing file without --force: {target}")

    for relative, content in sorted(file_map.items()):
        target = workspace / relative
        if dry_run:
            print(target)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        if relative in MANAGED_EXECUTABLES:
            target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def write_email_env(workspace: Path, content: str, *, dry_run: bool) -> None:
    target = workspace / ".codex_monitor" / "email.env"
    if dry_run:
        print(target)
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    target.chmod(0o600)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("workspace", help="Target workspace path.")
    parser.add_argument("--label", default="Long Job", help="Human-facing label used in reports and timer descriptions.")
    parser.add_argument("--systemd-basename", default="codex-long-job-monitor", help="User systemd unit basename without suffix.")
    parser.add_argument("--job-service", default="", help="Optional user systemd service name for the long-running job.")
    parser.add_argument("--primary-log", default="", help="Primary log path relative to the workspace.")
    parser.add_argument("--progress-log", default="", help="Optional progress timeline log path relative to the workspace.")
    parser.add_argument("--artifact-dir", dest="artifact_dirs", action="append", default=None, help="Artifact directory relative to the workspace. May be repeated.")
    parser.add_argument("--process-grep", default="python|bash|codex", help="grep -E pattern for job processes.")
    parser.add_argument("--codex-model", default="gpt-5.4-mini", help="Model name used by codex exec inside the monitor.")
    parser.add_argument("--run-command", default="echo 'Edit .codex_monitor/run_command.sh with the real long-running command.' >&2; exit 2", help="Shell command executed by run_with_monitor.sh.")
    parser.add_argument("--goal-mode", action="store_true", help="Enable Codex goal-status detection for complete, blocked, and usageLimited terminal emails.")
    parser.add_argument("--sender-email", default="", help="SMTP sender email. If set together with recipient and password, email.env is written automatically.")
    parser.add_argument("--recipient-email", default="", help="SMTP recipient email.")
    parser.add_argument("--sender-password", default="", help="SMTP password or authorization code for the sender email.")
    parser.add_argument("--smtp-host", default="", help="Optional SMTP host override.")
    parser.add_argument("--smtp-port", type=int, default=0, help="Optional SMTP port override.")
    parser.add_argument("--smtp-security", default="", choices=("", "starttls", "ssl", "none"), help="Optional SMTP security override.")
    parser.add_argument("--force", action="store_true", help="Overwrite managed files in the target workspace.")
    parser.add_argument("--dry-run", action="store_true", help="Print managed file paths without writing them.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    workspace = Path(args.workspace).expanduser().resolve()
    if not workspace.exists() or not workspace.is_dir():
        raise SystemExit(f"workspace is missing or not a directory: {workspace}")

    artifact_dirs = tuple(args.artifact_dirs or ["logs", "outputs", "reports", "results", "artifacts"])
    config = InstallConfig(
        workspace=workspace,
        label=args.label,
        systemd_basename=args.systemd_basename,
        job_service=args.job_service,
        primary_log=args.primary_log,
        progress_log=args.progress_log,
        artifact_dirs=artifact_dirs,
        process_grep=args.process_grep,
        codex_model=args.codex_model,
        run_command=args.run_command,
        goal_mode=args.goal_mode,
    )
    file_map = build_file_map(config)
    write_files(workspace, file_map, force=args.force, dry_run=args.dry_run)

    email_values = [args.sender_email, args.recipient_email, args.sender_password]
    resolved_smtp: tuple[str | None, int | None, str | None] = (None, None, None)
    if any(email_values) and not all(email_values):
        raise SystemExit("sender-email, recipient-email, and sender-password must be provided together")
    if all(email_values):
        resolved_smtp = infer_smtp(args.sender_email)
        smtp_host = args.smtp_host or resolved_smtp[0]
        smtp_port = args.smtp_port or resolved_smtp[1]
        smtp_security = args.smtp_security or resolved_smtp[2]
        email_env = build_email_env(
            sender_email=args.sender_email,
            recipient_email=args.recipient_email,
            sender_password=args.sender_password,
            smtp_host=smtp_host,
            smtp_port=smtp_port,
            smtp_security=smtp_security,
        )
        write_email_env(workspace, email_env, dry_run=args.dry_run)

    if not args.dry_run:
        print_install_summary(
            workspace,
            config,
            email_enabled=all(email_values),
            smtp_host=resolved_smtp[0] if not args.smtp_host else args.smtp_host,
            smtp_port=resolved_smtp[1] if not args.smtp_port else args.smtp_port,
            smtp_security=resolved_smtp[2] if not args.smtp_security else args.smtp_security,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
